In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
sys.path.append("../../../")
from src.models.gpt import GPT, GPT2BPETokenizer
import src.experiments.textgenutils as gutils

In [3]:
import requests
import zipfile
import os
from pathlib import Path

url = "https://archive.ics.uci.edu/static/public/228/sms+spam+collection.zip"
zip_path = "sms_spam_collection.zip"
extracted_path = "sms_spam_collection"
data_file_path = Path(extracted_path) / "SMSSpamCollection.tsv"


def download_and_unzip_spam_data(url, zip_path, extracted_path, data_file_path):
    if data_file_path.exists():
        print(f"{data_file_path} already exists. Skipping download and extraction.")
        return

    # Downloading the file
    response = requests.get(url, stream=True, timeout=60)
    response.raise_for_status()
    with open(zip_path, "wb") as out_file:
        for chunk in response.iter_content(chunk_size=8192):
            if chunk:
                out_file.write(chunk)

    # Unzipping the file
    with zipfile.ZipFile(zip_path, "r") as zip_ref:
        zip_ref.extractall(extracted_path)

    # Add .tsv file extension
    original_file_path = Path(extracted_path) / "SMSSpamCollection"
    os.rename(original_file_path, data_file_path)
    print(f"File downloaded and saved as {data_file_path}")


try:
    download_and_unzip_spam_data(url, zip_path, extracted_path, data_file_path)
except (requests.exceptions.RequestException, TimeoutError) as e:
    print(f"Primary URL failed: {e}. Trying backup URL...")
    url = "https://f001.backblazeb2.com/file/LLMs-from-scratch/sms%2Bspam%2Bcollection.zip"
    download_and_unzip_spam_data(url, zip_path, extracted_path, data_file_path)

sms_spam_collection/SMSSpamCollection.tsv already exists. Skipping download and extraction.

In [4]:
import pandas as pd

df = pd.read_csv(data_file_path, sep="\t", header=None, names=["Label", "Text"])
df

     Label                                               Text
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [5]:
print(df["Label"].value_counts())

Label
ham     4825
spam     747
Name: count, dtype: int64

In [6]:
def create_balanced_dataset(df):
    
    # Count the instances of "spam"
    num_spam = df[df["Label"] == "spam"].shape[0]
    
    # Randomly sample "ham" instances to match the number of "spam" instances
    ham_subset = df[df["Label"] == "ham"].sample(num_spam, random_state=123)
    
    # Combine ham "subset" with "spam"
    balanced_df = pd.concat([ham_subset, df[df["Label"] == "spam"]])

    return balanced_df


balanced_df = create_balanced_dataset(df)
print(balanced_df["Label"].value_counts())

Label
ham     747
spam    747
Name: count, dtype: int64

In [7]:
balanced_df["Label"] = balanced_df["Label"].map({"ham": 0, "spam": 1})
balanced_df

      Label                                               Text
4307      0  Awww dat is sweet! We can think of something t...
4138      0                             Just got to  &lt;#&gt;
4831      0  The word "Checkmate" in chess comes from the P...
4461      0  This is wishing you a great day. Moji told me ...
5440      0      Thank you. do you generally date the brothas?
...     ...                                                ...
5537      1  Want explicit SEX in 30 secs? Ring 02073162414...
5540      1  ASKED 3MOBILE IF 0870 CHATLINES INCLU IN FREE ...
5547      1  Had your contract mobile 11 Mnths? Latest Moto...
5566      1  REMINDER FROM O2: To get 2.50 pounds free call...
5567      1  This is the 2nd time we have tried 2 contact u...

[1494 rows x 2 columns]

In [8]:
def random_split(df, train_frac, validation_frac):
    # Shuffle the entire DataFrame
    df = df.sample(frac=1, random_state=123).reset_index(drop=True)

    # Calculate split indices
    train_end = int(len(df) * train_frac)
    validation_end = train_end + int(len(df) * validation_frac)

    # Split the DataFrame
    train_df = df[:train_end]
    validation_df = df[train_end:validation_end]
    test_df = df[validation_end:]

    return train_df, validation_df, test_df

train_df, validation_df, test_df = random_split(balanced_df, 0.7, 0.1)
# Test size is implied to be 0.2 as the remainder

train_df.to_csv("train.csv", index=None)
validation_df.to_csv("validation.csv", index=None)
test_df.to_csv("test.csv", index=None)

In [9]:
train_df

      Label                                               Text
0         0                Dude how do you like the buff wind.
1         0  Tessy..pls do me a favor. Pls convey my birthd...
2         1  Reminder: You have not downloaded the content ...
3         1  Got what it takes 2 take part in the WRC Rally...
4         1  Shop till u Drop, IS IT YOU, either 10K, 5K, £...
...     ...                                                ...
1040      1  4mths half price Orange line rental & latest c...
1041      1  Thanks for the Vote. Now sing along with the s...
1042      1  IMPORTANT INFORMATION 4 ORANGE USER 0796XXXXXX...
1043      1  Urgent! call 09066612661 from landline. Your c...
1044      0  His frens go then he in lor. Not alone wif my ...

[1045 rows x 2 columns]

In [10]:
import tiktoken

tokenizer = tiktoken.get_encoding("gpt2")
print(tokenizer.encode("<|endoftext|>", allowed_special={"<|endoftext|>"}))

[50256]

In [11]:
import torch
from torch.utils.data import Dataset


class SpamDataset(Dataset):
    def __init__(self, csv_file, tokenizer, max_length=None, pad_token_id=50256):
        self.data = pd.read_csv(csv_file)

        # Pre-tokenize texts
        self.encoded_texts = [
            tokenizer.encode(text) for text in self.data["Text"]
        ]

        if max_length is None:
            self.max_length = self._longest_encoded_length()
        else:
            self.max_length = max_length
            # Truncate sequences if they are longer than max_length
            self.encoded_texts = [
                encoded_text[:self.max_length]
                for encoded_text in self.encoded_texts
            ]

        # Pad sequences to the longest sequence
        self.encoded_texts = [
            encoded_text + [pad_token_id] * (self.max_length - len(encoded_text))
            for encoded_text in self.encoded_texts
        ]

    def __getitem__(self, index):
        encoded = self.encoded_texts[index]
        label = self.data.iloc[index]["Label"]
        return (
            torch.tensor(encoded, dtype=torch.long),
            torch.tensor(label, dtype=torch.long)
        )

    def __len__(self):
        return len(self.data)

    def _longest_encoded_length(self):
        max_length = 0
        for encoded_text in self.encoded_texts:
            encoded_length = len(encoded_text)
            if encoded_length > max_length:
                max_length = encoded_length
        return max_length
        # Note: A more pythonic version to implement this method
        # is the following, which is also used in the next chapter:
        # return max(len(encoded_text) for encoded_text in self.encoded_texts)

In [12]:
train_dataset = SpamDataset(
    csv_file="train.csv",
    max_length=None,
    tokenizer=tokenizer
)

print(train_dataset.max_length)

120

In [13]:
val_dataset = SpamDataset(
    csv_file="validation.csv",
    max_length=train_dataset.max_length,
    tokenizer=tokenizer
)
test_dataset = SpamDataset(
    csv_file="test.csv",
    max_length=train_dataset.max_length,
    tokenizer=tokenizer
)

In [14]:
from torch.utils.data import DataLoader

num_workers = 0
batch_size = 8

torch.manual_seed(123)

train_loader = DataLoader(
    dataset=train_dataset,
    batch_size=batch_size,
    shuffle=True,
    num_workers=num_workers,
    drop_last=True,
)

val_loader = DataLoader(
    dataset=val_dataset,
    batch_size=batch_size,
    num_workers=num_workers,
    drop_last=False,
)

test_loader = DataLoader(
    dataset=test_dataset,
    batch_size=batch_size,
    num_workers=num_workers,
    drop_last=False,
)

In [15]:
print("Train loader:")
for input_batch, target_batch in train_loader:
    pass

print("Input batch dimensions:", input_batch.shape)
print("Label batch dimensions", target_batch.shape)

Train loader:
Input batch dimensions: torch.Size([8, 120])
Label batch dimensions torch.Size([8])

In [16]:
print(f"{len(train_loader)} training batches")
print(f"{len(val_loader)} validation batches")
print(f"{len(test_loader)} test batches")

130 training batches
19 validation batches
38 test batches

In [17]:
model = GPT.from_pretrained("gpt2").cuda()

/home/nyxx/anaconda3/envs/gen/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Loading weights: 100%|██████████| 148/148 [00:00<00:00, 502.24it/s, Materializing param=transformer.wte.weight]

In [18]:
model.eval()

GPT(
  (dropout): Dropout(p=0.1, inplace=False)
  (word_embeddings): Embedding(50257, 768)
  (position_embeddings): Embedding(1024, 768)
  (decoder_blocks): ModuleList(
    (0-11): 12 x DecoderBlock(
      (dropout): Dropout(p=0.1, inplace=False)
      (ln1): LayerNorm()
      (attn): MultiheadAttention(embed_dim=768, n_heads=12)
      (ln2): LayerNorm()
      (ffn): FeedForwardBlock(
        (linear1): Linear(in_features=768, out_features=3072, bias=True)
        (linear2): Linear(in_features=3072, out_features=768, bias=True)
      )
    )
  )
  (layer_norm): LayerNorm()
)

In [19]:
def gen_text(prompt, n_tokens_to_generate):
    tokenizer = GPT2BPETokenizer()
    indices = tokenizer.encode(prompt)
    generator = gutils.generate_text(model, tokenizer, prompt,
                                        n_tokens_to_gen=n_tokens_to_generate,
                                        top_k=100,
                                        top_p=0.95,
                                        sample=True,
                                        print_stream=False,
                                        use_kv_cache=False)

    response = ''.join(list(generator))

    print('Response:', response.lstrip())

In [20]:
sys.path.append("../../../")
import src

In [21]:
USER_NAME = 'John'
ASST_NAME = 'Taylor'

SYSTEM_MESSAGE = (f'Two friends, {USER_NAME} and {ASST_NAME}, are having an online conversation. '
                  f'{ASST_NAME} is friendly, talkative, and loves to ask {USER_NAME} questions.')
chat_template = src.nlp.chattemplates.SimpleConversationTemplate(USER_NAME, ASST_NAME, SYSTEM_MESSAGE)  

def start_conversation(profile_pic: str = '🙂'):
    gutils.interactive_conversation(
        model, chat_template, tokenizer,
        user_name=USER_NAME,
        profile_pic=profile_pic,
        user_bg_color='yellow',
        asst_name=ASST_NAME,
        asst_profile_pic='⚪',
        asst_bg_color='bluegreen',
        max_response_length=100,
        top_k=100,
        top_p=0.98,
        temperature=0.8,
        stop_strings={'\n': 1, '<|endoftext|>': 1, '\.|\!|\?': 3},
    )

<>:21: SyntaxWarning: invalid escape sequence '\.'
<>:21: SyntaxWarning: invalid escape sequence '\.'
/tmp/ipykernel_590372/631857779.py:21: SyntaxWarning: invalid escape sequence '\.'
  stop_strings={'\n': 1, '<|endoftext|>': 1, '\.|\!|\?': 3},

In [22]:
# Sanity checks for GPT-2 large loading
import torch

print('Model class:', type(model).__name__)
print('n_layers:', model.n_layers, 'n_heads:', model.n_heads, 'embed_dim:', model.embed_dim)
print('vocab_size:', model.vocab_size, 'block_size:', model.block_size)

param_count = sum(p.numel() for p in model.parameters())
print('Total parameters:', f"{param_count:,}")

same_storage = model.word_embeddings.weight.data_ptr() == model.output_projection.data_ptr()
print('Tied input/output embeddings:', same_storage)

first_param = next(model.parameters())
print('First parameter device:', first_param.device)
print('Model in eval mode:', not model.training)

Model class: GPT
n_layers: 12 n_heads: 12 embed_dim: 768
vocab_size: 50257 block_size: 1024
Total parameters: 124,458,240
Tied input/output embeddings: True
First parameter device: cuda:0
Model in eval mode: True

In [23]:
# Quick forward-pass sanity check
with torch.no_grad():
    test_ids = torch.tensor([[15496, 11, 995]], device=next(model.parameters()).device, dtype=torch.long)  # "Hello, world"
    logits = model(test_ids, use_kv_cache=False)

print('Logits shape:', tuple(logits.shape))
print('Logits finite:', torch.isfinite(logits).all().item())
print('Any NaN:', torch.isnan(logits).any().item())

Logits shape: (1, 3, 50257)
Logits finite: True
Any NaN: False

In [24]:
start_conversation(profile_pic='👦🏻')

< You are now talking with Taylor. Send 'bye' to exit, 'clear' to reset cache. >

👦🏻 John: bye

< / end of conversation. >

In [25]:
for param in model.parameters():
    param.requires_grad = False

In [26]:
sd_model = model.state_dict()

In [27]:
for key, val in model.named_parameters():
    print(key, val.shape)

output_projection torch.Size([50257, 768])
position_embeddings.weight torch.Size([1024, 768])
decoder_blocks.0.ln1.weight torch.Size([768])
decoder_blocks.0.ln1.bias torch.Size([768])
decoder_blocks.0.attn.norm.weight torch.Size([768])
decoder_blocks.0.attn.norm.bias torch.Size([768])
decoder_blocks.0.attn.to_qkv.weight torch.Size([2304, 768])
decoder_blocks.0.attn.to_qkv.bias torch.Size([2304])
decoder_blocks.0.attn.to_out.weight torch.Size([768, 768])
decoder_blocks.0.attn.to_out.bias torch.Size([768])
decoder_blocks.0.ln2.weight torch.Size([768])
decoder_blocks.0.ln2.bias torch.Size([768])
decoder_blocks.0.ffn.linear1.weight torch.Size([3072, 768])
decoder_blocks.0.ffn.linear1.bias torch.Size([3072])
decoder_blocks.0.ffn.linear2.weight torch.Size([768, 3072])
decoder_blocks.0.ffn.linear2.bias torch.Size([768])
decoder_blocks.1.ln1.weight torch.Size([768])
decoder_blocks.1.ln1.bias torch.Size([768])
decoder_blocks.1.attn.norm.weight torch.Size([768])
decoder_blocks.1.attn.norm.bias torch.Size([768])
decoder_blocks.1.attn.to_qkv.weight torch.Size([2304, 768])
decoder_blocks.1.attn.to_qkv.bias torch.Size([2304])
decoder_blocks.1.attn.to_out.weight torch.Size([768, 768])
decoder_blocks.1.attn.to_out.bias torch.Size([768])
decoder_blocks.1.ln2.weight torch.Size([768])
decoder_blocks.1.ln2.bias torch.Size([768])
decoder_blocks.1.ffn.linear1.weight torch.Size([3072, 768])
decoder_blocks.1.ffn.linear1.bias torch.Size([3072])
decoder_blocks.1.ffn.linear2.weight torch.Size([768, 3072])
decoder_blocks.1.ffn.linear2.bias torch.Size([768])
decoder_blocks.2.ln1.weight torch.Size([768])
decoder_blocks.2.ln1.bias torch.Size([768])
decoder_blocks.2.attn.norm.weight torch.Size([768])
decoder_blocks.2.attn.norm.bias torch.Size([768])
decoder_blocks.2.attn.to_qkv.weight torch.Size([2304, 768])
decoder_blocks.2.attn.to_qkv.bias torch.Size([2304])
decoder_blocks.2.attn.to_out.weight torch.Size([768, 768])
decoder_blocks.2.attn.to_out.bias torch.Size([768])
decoder_blocks.2.ln2.weight torch.Size([768])
decoder_blocks.2.ln2.bias torch.Size([768])
decoder_blocks.2.ffn.linear1.weight torch.Size([3072, 768])
decoder_blocks.2.ffn.linear1.bias torch.Size([3072])
decoder_blocks.2.ffn.linear2.weight torch.Size([768, 3072])
decoder_blocks.2.ffn.linear2.bias torch.Size([768])
decoder_blocks.3.ln1.weight torch.Size([768])
decoder_blocks.3.ln1.bias torch.Size([768])
decoder_blocks.3.attn.norm.weight torch.Size([768])
decoder_blocks.3.attn.norm.bias torch.Size([768])
decoder_blocks.3.attn.to_qkv.weight torch.Size([2304, 768])
decoder_blocks.3.attn.to_qkv.bias torch.Size([2304])
decoder_blocks.3.attn.to_out.weight torch.Size([768, 768])
decoder_blocks.3.attn.to_out.bias torch.Size([768])
decoder_blocks.3.ln2.weight torch.Size([768])
decoder_blocks.3.ln2.bias torch.Size([768])
decoder_blocks.3.ffn.linear1.weight torch.Size([3072, 768])
decoder_blocks.3.ffn.linear1.bias torch.Size([3072])
decoder_blocks.3.ffn.linear2.weight torch.Size([768, 3072])
decoder_blocks.3.ffn.linear2.bias torch.Size([768])
decoder_blocks.4.ln1.weight torch.Size([768])
decoder_blocks.4.ln1.bias torch.Size([768])
decoder_blocks.4.attn.norm.weight torch.Size([768])
decoder_blocks.4.attn.norm.bias torch.Size([768])
decoder_blocks.4.attn.to_qkv.weight torch.Size([2304, 768])
decoder_blocks.4.attn.to_qkv.bias torch.Size([2304])
decoder_blocks.4.attn.to_out.weight torch.Size([768, 768])
decoder_blocks.4.attn.to_out.bias torch.Size([768])
decoder_blocks.4.ln2.weight torch.Size([768])
decoder_blocks.4.ln2.bias torch.Size([768])
decoder_blocks.4.ffn.linear1.weight torch.Size([3072, 768])
decoder_blocks.4.ffn.linear1.bias torch.Size([3072])
decoder_blocks.4.ffn.linear2.weight torch.Size([768, 3072])
decoder_blocks.4.ffn.linear2.bias torch.Size([768])
decoder_blocks.5.ln1.weight torch.Size([768])
decoder_blocks.5.ln1.bias torch.Size([768])
decoder_blocks.5.attn.norm.weight torch.Size([768])
decoder_blocks.5.attn.norm.bias torch.Size([768])
decoder_blocks.5.attn.to_qkv.weight torch.Size([2304, 768])
decoder_blocks.5.attn.to_qkv.bias torch.Size([2304])
decoder_blocks.5.attn.to_out.weight torch.Size([768, 768])
decoder_blocks.5.attn.to_out.bias torch.Size([768])
decoder_blocks.5.ln2.weight torch.Size([768])
decoder_blocks.5.ln2.bias torch.Size([768])
decoder_blocks.5.ffn.linear1.weight torch.Size([3072, 768])
decoder_blocks.5.ffn.linear1.bias torch.Size([3072])
decoder_blocks.5.ffn.linear2.weight torch.Size([768, 3072])
decoder_blocks.5.ffn.linear2.bias torch.Size([768])
decoder_blocks.6.ln1.weight torch.Size([768])
decoder_blocks.6.ln1.bias torch.Size([768])
decoder_blocks.6.attn.norm.weight torch.Size([768])
decoder_blocks.6.attn.norm.bias torch.Size([768])
decoder_blocks.6.attn.to_qkv.weight torch.Size([2304, 768])
decoder_blocks.6.attn.to_qkv.bias torch.Size([2304])
decoder_blocks.6.attn.to_out.weight torch.Size([768, 768])
decoder_blocks.6.attn.to_out.bias torch.Size([768])
decoder_blocks.6.ln2.weight torch.Size([768])
decoder_blocks.6.ln2.bias torch.Size([768])
decoder_blocks.6.ffn.linear1.weight torch.Size([3072, 768])
decoder_blocks.6.ffn.linear1.bias torch.Size([3072])
decoder_blocks.6.ffn.linear2.weight torch.Size([768, 3072])
decoder_blocks.6.ffn.linear2.bias torch.Size([768])
decoder_blocks.7.ln1.weight torch.Size([768])
decoder_blocks.7.ln1.bias torch.Size([768])
decoder_blocks.7.attn.norm.weight torch.Size([768])
decoder_blocks.7.attn.norm.bias torch.Size([768])
decoder_blocks.7.attn.to_qkv.weight torch.Size([2304, 768])
decoder_blocks.7.attn.to_qkv.bias torch.Size([2304])
decoder_blocks.7.attn.to_out.weight torch.Size([768, 768])
decoder_blocks.7.attn.to_out.bias torch.Size([768])
decoder_blocks.7.ln2.weight torch.Size([768])
decoder_blocks.7.ln2.bias torch.Size([768])
decoder_blocks.7.ffn.linear1.weight torch.Size([3072, 768])
decoder_blocks.7.ffn.linear1.bias torch.Size([3072])
decoder_blocks.7.ffn.linear2.weight torch.Size([768, 3072])
decoder_blocks.7.ffn.linear2.bias torch.Size([768])
decoder_blocks.8.ln1.weight torch.Size([768])
decoder_blocks.8.ln1.bias torch.Size([768])
decoder_blocks.8.attn.norm.weight torch.Size([768])
decoder_blocks.8.attn.norm.bias torch.Size([768])
decoder_blocks.8.attn.to_qkv.weight torch.Size([2304, 768])
decoder_blocks.8.attn.to_qkv.bias torch.Size([2304])
decoder_blocks.8.attn.to_out.weight torch.Size([768, 768])
decoder_blocks.8.attn.to_out.bias torch.Size([768])
decoder_blocks.8.ln2.weight torch.Size([768])
decoder_blocks.8.ln2.bias torch.Size([768])
decoder_blocks.8.ffn.linear1.weight torch.Size([3072, 768])
decoder_blocks.8.ffn.linear1.bias torch.Size([3072])
decoder_blocks.8.ffn.linear2.weight torch.Size([768, 3072])
decoder_blocks.8.ffn.linear2.bias torch.Size([768])
decoder_blocks.9.ln1.weight torch.Size([768])
decoder_blocks.9.ln1.bias torch.Size([768])
decoder_blocks.9.attn.norm.weight torch.Size([768])
decoder_blocks.9.attn.norm.bias torch.Size([768])
decoder_blocks.9.attn.to_qkv.weight torch.Size([2304, 768])
decoder_blocks.9.attn.to_qkv.bias torch.Size([2304])
decoder_blocks.9.attn.to_out.weight torch.Size([768, 768])
decoder_blocks.9.attn.to_out.bias torch.Size([768])
decoder_blocks.9.ln2.weight torch.Size([768])
decoder_blocks.9.ln2.bias torch.Size([768])
decoder_blocks.9.ffn.linear1.weight torch.Size([3072, 768])
decoder_blocks.9.ffn.linear1.bias torch.Size([3072])
decoder_blocks.9.ffn.linear2.weight torch.Size([768, 3072])
decoder_blocks.9.ffn.linear2.bias torch.Size([768])
decoder_blocks.10.ln1.weight torch.Size([768])
decoder_blocks.10.ln1.bias torch.Size([768])
decoder_blocks.10.attn.norm.weight torch.Size([768])
decoder_blocks.10.attn.norm.bias torch.Size([768])
decoder_blocks.10.attn.to_qkv.weight torch.Size([2304, 768])
decoder_blocks.10.attn.to_qkv.bias torch.Size([2304])
decoder_blocks.10.attn.to_out.weight torch.Size([768, 768])
decoder_blocks.10.attn.to_out.bias torch.Size([768])
decoder_blocks.10.ln2.weight torch.Size([768])
decoder_blocks.10.ln2.bias torch.Size([768])
decoder_blocks.10.ffn.linear1.weight torch.Size([3072, 768])
decoder_blocks.10.ffn.linear1.bias torch.Size([3072])
decoder_blocks.10.ffn.linear2.weight torch.Size([768, 3072])
decoder_blocks.10.ffn.linear2.bias torch.Size([768])
decoder_blocks.11.ln1.weight torch.Size([768])
decoder_blocks.11.ln1.bias torch.Size([768])
decoder_blocks.11.attn.norm.weight torch.Size([768])
decoder_blocks.11.attn.norm.bias torch.Size([768])
decoder_blocks.11.attn.to_qkv.weight torch.Size([2304, 768])
decoder_blocks.11.attn.to_qkv.bias torch.Size([2304])
decoder_blocks.11.attn.to_out.weight torch.Size([768, 768])
decoder_blocks.11.attn.to_out.bias torch.Size([768])
decoder_blocks.11.ln2.weight torch.Size([768])
decoder_blocks.11.ln2.bias torch.Size([768])
decoder_blocks.11.ffn.linear1.weight torch.Size([3072, 768])
decoder_blocks.11.ffn.linear1.bias torch.Size([3072])
decoder_blocks.11.ffn.linear2.weight torch.Size([768, 3072])
decoder_blocks.11.ffn.linear2.bias torch.Size([768])
layer_norm.weight torch.Size([768])
layer_norm.bias torch.Size([768])

In [28]:
torch.manual_seed(123)

num_classes = 2
device = next(model.parameters()).device
model.clear_kv_cache()

# output_projection is a Parameter in this GPT implementation, not an nn.Module
model.output_projection = torch.nn.Parameter(
    torch.empty(num_classes, model.embed_dim, device=device)
)
torch.nn.init.normal_(model.output_projection, mean=0.0, std=0.02)

Parameter containing:
tensor([[ 0.0268,  0.0041, -0.0338,  ..., -0.0085, -0.0012,  0.0157],
        [ 0.0080, -0.0057, -0.0146,  ...,  0.0105,  0.0460,  0.0126]],
       device='cuda:0', requires_grad=True)

In [29]:
model

GPT(
  (dropout): Dropout(p=0.1, inplace=False)
  (word_embeddings): Embedding(50257, 768)
  (position_embeddings): Embedding(1024, 768)
  (decoder_blocks): ModuleList(
    (0-11): 12 x DecoderBlock(
      (dropout): Dropout(p=0.1, inplace=False)
      (ln1): LayerNorm()
      (attn): MultiheadAttention(embed_dim=768, n_heads=12)
      (ln2): LayerNorm()
      (ffn): FeedForwardBlock(
        (linear1): Linear(in_features=768, out_features=3072, bias=True)
        (linear2): Linear(in_features=3072, out_features=768, bias=True)
      )
    )
  )
  (layer_norm): LayerNorm()
)

In [30]:
for param in model.decoder_blocks[-1].parameters():
    param.requires_grad = True

for param in model.layer_norm.parameters():
    param.requires_grad = True

In [31]:
inputs = tokenizer.encode("Do you have time")
inputs = torch.tensor(inputs).unsqueeze(0).cuda()
print("Inputs:", inputs)
print("Inputs dimensions:", inputs.shape) # shape: (batch_size, num_tokens)

Inputs: tensor([[5211,  345,  423,  640]], device='cuda:0')
Inputs dimensions: torch.Size([1, 4])

In [32]:
with torch.no_grad():
    model.clear_kv_cache()
    outputs = model(inputs, use_kv_cache=False)

print("Outputs:\n", outputs)
print("Outputs dimensions:", outputs.shape) # shape: (batch_size, num_tokens, num_classes)

Outputs:
 tensor([[[-1.2555,  2.2349],
         [-3.7807,  6.4925],
         [-1.8325,  4.8992],
         [-2.4574,  5.1563]]], device='cuda:0')
Outputs dimensions: torch.Size([1, 4, 2])

In [33]:
print("Last output token:", outputs[:, -1, :])

Last output token: tensor([[-2.4574,  5.1563]], device='cuda:0')

In [34]:
probas = torch.softmax(outputs[:, -1, :], dim=-1)
label = torch.argmax(probas)
print("Class label:", label.item())

Class label: 1

In [35]:
def calc_accuracy_loader(data_loader, model, device, num_batches=None):
    model.eval()
    correct_predictions, num_examples = 0, 0

    if num_batches is None:
        num_batches = len(data_loader)
    else:
        num_batches = min(num_batches, len(data_loader))
    for i, (input_batch, target_batch) in enumerate(data_loader):
        if i < num_batches:
            input_batch, target_batch = input_batch.to(device), target_batch.to(device)

            with torch.no_grad():
                model.clear_kv_cache()
                logits = model(input_batch, use_kv_cache=False)[:, -1, :]  # Logits of last output token
            predicted_labels = torch.argmax(logits, dim=-1)

            num_examples += predicted_labels.shape[0]
            correct_predictions += (predicted_labels == target_batch).sum().item()
        else:
            break
    return correct_predictions / num_examples

In [36]:
if torch.cuda.is_available():
    device = torch.device("cuda")
elif torch.backends.mps.is_available():
    # Use PyTorch 2.9 or newer for stable mps results
    major, minor = map(int, torch.__version__.split(".")[:2])
    if (major, minor) >= (2, 9):
        device = torch.device("mps")
    else:
        device = torch.device("cpu")
else:
    device = torch.device("cpu")

print("Device:", device)

model.to(device) # no assignment model = model.to(device) necessary for nn.Module classes

torch.manual_seed(123) # For reproducibility due to the shuffling in the training data loader

train_accuracy = calc_accuracy_loader(train_loader, model, device, num_batches=10)
val_accuracy = calc_accuracy_loader(val_loader, model, device, num_batches=10)
test_accuracy = calc_accuracy_loader(test_loader, model, device, num_batches=10)

print(f"Training accuracy: {train_accuracy*100:.2f}%")
print(f"Validation accuracy: {val_accuracy*100:.2f}%")
print(f"Test accuracy: {test_accuracy*100:.2f}%")

Device: cuda
Training accuracy: 46.25%
Validation accuracy: 45.00%
Test accuracy: 48.75%

In [37]:
def calc_loss_batch(input_batch, target_batch, model, device):
    input_batch, target_batch = input_batch.to(device), target_batch.to(device)
    logits = model(input_batch)[:, -1, :]  # Logits of last output token
    loss = torch.nn.functional.cross_entropy(logits, target_batch)
    return loss

In [38]:
def calc_loss_loader(data_loader, model, device, num_batches=None):
    total_loss = 0.
    if len(data_loader) == 0:
        return float("nan")
    elif num_batches is None:
        num_batches = len(data_loader)
    else:
        # Reduce the number of batches to match the total number of batches in the data loader
        # if num_batches exceeds the number of batches in the data loader
        num_batches = min(num_batches, len(data_loader))
    for i, (input_batch, target_batch) in enumerate(data_loader):
        if i < num_batches:
            loss = calc_loss_batch(input_batch, target_batch, model, device)
            total_loss += loss.item()
        else:
            break
    return total_loss / num_batches

In [ ]:
with torch.no_grad(): # Disable gradient tracking for efficiency because we are not training, yet
    train_loss = calc_loss_loader(train_loader, model, device, num_batches=5)
    val_loss = calc_loss_loader(val_loader, model, device, num_batches=5)
    test_loss = calc_loss_loader(test_loader, model, device, num_batches=5)

print(f"Training loss: {train_loss:.3f}")
print(f"Validation loss: {val_loss:.3f}")
print(f"Test loss: {test_loss:.3f}")

In [ ]:
def evaluate_model(model, train_loader, val_loader, device, eval_iter):
    model.eval()
    with torch.no_grad():
        train_loss = calc_loss_loader(train_loader, model, device, num_batches=eval_iter)
        val_loss = calc_loss_loader(val_loader, model, device, num_batches=eval_iter)
    model.train()
    return train_loss, val_loss

In [ ]:
import time

start_time = time.time()

torch.manual_seed(123)

optimizer = torch.optim.AdamW(model.parameters(), lr=5e-5, weight_decay=0.1)

num_epochs = 5
train_losses, val_losses, train_accs, val_accs, examples_seen = train_classifier_simple(
    model, train_loader, val_loader, optimizer, device,
    num_epochs=num_epochs, eval_freq=50, eval_iter=5,
)

end_time = time.time()
execution_time_minutes = (end_time - start_time) / 60
print(f"Training completed in {execution_time_minutes:.2f} minutes.")

In [ ]:
import matplotlib.pyplot as plt

def plot_values(epochs_seen, examples_seen, train_values, val_values, label="loss"):
    fig, ax1 = plt.subplots(figsize=(5, 3))

    # Plot training and validation loss against epochs
    ax1.plot(epochs_seen, train_values, label=f"Training {label}")
    ax1.plot(epochs_seen, val_values, linestyle="-.", label=f"Validation {label}")
    ax1.set_xlabel("Epochs")
    ax1.set_ylabel(label.capitalize())
    ax1.legend()

    # Create a second x-axis for examples seen
    ax2 = ax1.twiny()  # Create a second x-axis that shares the same y-axis
    ax2.plot(examples_seen, train_values, alpha=0)  # Invisible plot for aligning ticks
    ax2.set_xlabel("Examples seen")

    fig.tight_layout()  # Adjust layout to make room
    plt.savefig(f"{label}-plot.pdf")
    plt.show()

In [ ]:
epochs_tensor = torch.linspace(0, num_epochs, len(train_losses))
examples_seen_tensor = torch.linspace(0, examples_seen, len(train_losses))

plot_values(epochs_tensor, examples_seen_tensor, train_losses, val_losses)

In [ ]:
epochs_tensor = torch.linspace(0, num_epochs, len(train_accs))
examples_seen_tensor = torch.linspace(0, examples_seen, len(train_accs))

plot_values(epochs_tensor, examples_seen_tensor, train_accs, val_accs, label="accuracy")

In [ ]:
train_accuracy = calc_accuracy_loader(train_loader, model, device)
val_accuracy = calc_accuracy_loader(val_loader, model, device)
test_accuracy = calc_accuracy_loader(test_loader, model, device)

print(f"Training accuracy: {train_accuracy*100:.2f}%")
print(f"Validation accuracy: {val_accuracy*100:.2f}%")
print(f"Test accuracy: {test_accuracy*100:.2f}%")

In [ ]:
def classify_review(text, model, tokenizer, device, max_length=None, pad_token_id=50256):
    model.eval()

    # Prepare inputs to the model
    input_ids = tokenizer.encode(text)
    supported_context_length = model.pos_emb.weight.shape[0]
    # Note: In the book, this was originally written as pos_emb.weight.shape[1] by mistake
    # It didn't break the code but would have caused unnecessary truncation (to 768 instead of 1024)

    # Truncate sequences if they too long
    input_ids = input_ids[:min(max_length, supported_context_length)]
    assert max_length is not None, (
        "max_length must be specified. If you want to use the full model context, "
        "pass max_length=model.pos_emb.weight.shape[0]."
    )
    assert max_length <= supported_context_length, (
        f"max_length ({max_length}) exceeds model's supported context length ({supported_context_length})."
    )    
    # Alternatively, a more robust version is the following one, which handles the max_length=None case better
    # max_len = min(max_length,supported_context_length) if max_length else supported_context_length
    # input_ids = input_ids[:max_len]
    
    # Pad sequences to the longest sequence
    input_ids += [pad_token_id] * (max_length - len(input_ids))
    input_tensor = torch.tensor(input_ids, device=device).unsqueeze(0) # add batch dimension

    # Model inference
    with torch.no_grad():
        logits = model(input_tensor)[:, -1, :]  # Logits of the last output token
    predicted_label = torch.argmax(logits, dim=-1).item()

    # Return the classified result
    return "spam" if predicted_label == 1 else "not spam"

In [ ]:
text_1 = (
    "You are a winner you have been specially"
    " selected to receive $1000 cash or a $2000 award."
)

print(classify_review(
    text_1, model, tokenizer, device, max_length=train_dataset.max_length
))

In [ ]:
text_2 = (
    "Hey, just wanted to check if we're still on"
    " for dinner tonight? Let me know!"
)

print(classify_review(
    text_2, model, tokenizer, device, max_length=train_dataset.max_length
))

In [ ]:
torch.save(model.state_dict(), "review_classifier.pth")

In [ ]:
model_state_dict = torch.load("review_classifier.pth", map_location=device, weights_only=True)
model.load_state_dict(model_state_dict)